Update metalava.yml.

diff --git a/.github/workflows/metalava.yml b/.github/workflows/metalava.yml
--- a/.github/workflows/metalava.yml
+++ b/.github/workflows/metalava.yml
@@ -20,20 +20,30 @@ jobs:
       - name: Check compatibility (Kotlin)
         id: compat-kotlin
         continue-on-error: true
-        run: ./gradlew metalavaCheckCompatibility
+        run: |
+          if ./gradlew metalavaCheckCompatibility 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibility FAILED'; then
+            echo "::set-output name=compat-error::$(grep -oP 'Aborting: .*(?=FAILED)' gradle_output.log)"
+            exit 1
+          fi
 
       - name: Check compatibility (Android)
         id: compat-android
         continue-on-error: true
-        run: ./gradlew metalavaCheckCompatibilityDebug
+        run: |
+          if ./gradlew metalavaCheckCompatibilityDebug 2>&1 | tee gradle_output.log | grep -q 'metalavaCheckCompatibilityDebug FAILED'; then
+            echo "::set-output name=compat-error::$(grep -oP 'Aborting: .*(?=FAILED)' gradle_output.log)"
+            exit 1
+          fi
 
       - name: Check for breaking change
         if: ${{ always() }}
         run: |
           if [[ "${{ steps.compat-kotlin.outcome }}" == "failure" ]]; then
             echo "One or more Kotlin libraries have a breaking change."
+            echo "${{ steps.compat-kotlin.outputs.compat-error }}"
           elif [[ "${{ steps.compat-android.outcome }}" == "failure" ]]; then
             echo "One or more Android libraries have a breaking change."
+            echo "${{ steps.compat-android.outputs.compat-error }}"
           else
             echo "No breaking changes detected."
           fi
