Update scripts-testing.yml

diff --git a/.github/workflows/scripts-testing.yml b/.github/workflows/scripts-testing.yml
--- a/.github/workflows/scripts-testing.yml
+++ b/.github/workflows/scripts-testing.yml
@@ -15,17 +15,60 @@ jobs:
         run: |
           # Define the function
           my_function() {
-            echo "This is a function call for $1"
+            echo "This is a function call for $1..."
             # Simulate some work
             sleep 2
+
+            if [[ $1 == +(second) ]]; then
+              echo "Function call for $1 failed!"
+              stop_jobs
+              exit 1
+            fi
+            
+            echo "Function call for $1 finished!"
+          }
+
+          # Function to handle the cleanup and final status
+          cleanup() {
+            STOP=$(<"$STOP_FILE")
+            if [[ "$STOP" == "true" ]]; then
+              echo "Stopped!"
+            fi
+            # Clean up the abort file
+            rm -f "$STOP_FILE"
+          }
+
+          # Stop jobs function
+          stop_jobs() {
+            echo "Stopping workflow..."
+            #echo "true" > "$STOP_FILE"
+            # Send a kill signal to all background jobs and terminate the script
+            kill 0
           }
 
           items=("first" "second" "third" "fourth" "fifth")
 
+          echo "Setting up semaphore..."
+          # Max concurrent jobs
+          MAX_JOBS=4
+          # Semaphore setup
+          SEMAPHORE=$(mktemp -u)  # Create a unique name for the semaphore
+          mkfifo "$SEMAPHORE"
+          exec 3<>"$SEMAPHORE"
+          rm "$SEMAPHORE"
+          for _ in $(seq $MAX_JOBS); do echo >&3; done
+
+          # Trap exit signal to call the cleanup function
+          trap cleanup EXIT
+
           for item in "${items[@]}"; do
+            # Wait for an available slot in the semaphore
+            read -u 3
             (
               # Call the function
               my_function $item
+
+              echo >&3  # Release the slot after the job is done
             ) &
           done
 
