Add missing package version id request

diff --git a/.github/workflows/smart-publish.yml b/.github/workflows/smart-publish.yml
--- a/.github/workflows/smart-publish.yml
+++ b/.github/workflows/smart-publish.yml
@@ -74,14 +74,24 @@ jobs:
           
               PACKAGE_NAME="com.example${module//:/\.}"
               ORG_NAME=${{ github.repository_owner }} 
-              VERSION=${{ github.event.inputs.version }} 
+          
+              # Fetch latest version ID of the package
+              echo "🔍 Fetching latest version ID of the $PACKAGE_NAME package..."
+              VERSION_ID=$(gh api \
+                -H "Accept: application/vnd.github+json" \
+                /orgs/$ORG_NAME/packages/maven/$PACKAGE_NAME/versions | jq -r '.[0].id')
+      
+              if [ -z "$VERSION_ID" ] || [ "$VERSION_ID" == "null" ]; then
+                echo "❌ Failed to get package version ID. Skipping delete."
+                exit 1
+              fi
           
               # Delete the conflicting package version
-              echo "🗑️ Deleting conflicting $PACKAGE_NAME package of version: v$VERSION"
+              echo "🗑️ Deleting conflicting package of version: v${{ github.event.inputs.version }}"
               gh api \
                 --method DELETE \
                 -H "Accept: application/vnd.github+json" \
-                /orgs/$ORG_NAME/packages/maven/$PACKAGE_NAME/versions/$VERSION
+                /orgs/$ORG_NAME/packages/maven/$PACKAGE_NAME/versions/$VERSION_ID
           
               # Retry the publish task after deletion
               echo "🔄 Retrying publish for $module..."
